### ISSUE TITLE
question with mariadb and folders

### ISSUE THREAD

**Issue by megamanzteam** [psybernoid/QNAPDocker#1]
Was following your guide and ran into a few issues. On Quts Hero 5.2.0.2860

First, do you think you could expand the create folder section? Please add recommended settings needed for the share. ex. thin vs thick, how large the filesystem should be, performance/block size, etc.

Second, in the mariadb section I am getting stuck. I setup my folder as "/container_data/mariadb_database:/config" to prep for future containers. It could be possible I set that wrong. Down the road I want to try doing nextcloud and have it connect to mariadb. Anyways, I do get errors that say it is a space issue (error 28). I have yet to proceed further in the guide yet, but looking forward to getting this all figured out.

PS. How did you get the coding to be in dark mode in quts?

Log:
```
database  | [migrations] started
database  | [migrations] no migrations found
database  | usermod: no changes
database  | ───────────────────────────────────────
database  | 
database  |       ██╗     ███████╗██╗ ██████╗
database  |       ██║     ██╔════╝██║██╔═══██╗
database  |       ██║     ███████╗██║██║   ██║
database  |       ██║     ╚════██║██║██║   ██║
database  |       ███████╗███████║██║╚██████╔╝
database  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
database  | 
database  |    Brought to you by linuxserver.io
database  | ───────────────────────────────────────
database  | 
database  | To support LSIO projects visit:
database  | https://www.linuxserver.io/donate/
database  | 
database  | ───────────────────────────────────────
database  | GID/UID
database  | ───────────────────────────────────────
database  | 
database  | User UID:    911
database  | User GID:    911
database  | ───────────────────────────────────────
database  | Linuxserver.io version: 10.11.8-r0-ls155
database  | Build-date: 2024-09-10T07:43:39+00:00
database  | ───────────────────────────────────────
database  |     
database  | Setting Up Initial Databases
database  | Installing MariaDB/MySQL system tables in '/config/databases' ...
database  | 2024-09-10 19:06:21 0 [ERROR] InnoDB: preallocating 100663296 bytes for file ./ib_logfile101 failed with error 28
database  | 2024-09-10 19:06:21 0 [ERROR] InnoDB: Cannot set log file ./ib_logfile101 size to 96.000MiB
database  | 2024-09-10 19:06:21 0 [ERROR] InnoDB: Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
database  | 2024-09-10 19:06:22 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
database  | 2024-09-10 19:06:22 0 [ERROR] Unknown/unsupported storage engine: InnoDB
database  | 2024-09-10 19:06:22 0 [ERROR] Aborting
database  | 
database  | Installation of system tables failed!  Examine the logs in
database  | /config/databases for more information.
database  | 
database  | The problem could be conflicting information in an external
database  | my.cnf files. You can ignore these by doing:
database  | 
database  |     shell> /usr/bin/mariadb-install-db --defaults-file=~/.my.cnf
database  | 
database  | You can also try to start the mariadbd daemon with:
database  | 
database  |     shell> /usr/bin/mariadbd --skip-grant-tables --general-log &
database  | 
database  | and use the command line tool /usr/bin/mariadb
database  | to connect to the mysql database and look at the grant tables:
database  | 
database  |     shell> /usr/bin/mariadb -u root mysql
database  |     MariaDB> show tables;
database  | 
database  | Try '/usr/bin/mariadbd --help' if you have problems with paths.  Using
database  | --general-log gives you a log in /config/databases that may be helpful.
database  | 
database  | The latest information about mysql_install_db is available at
database  | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
database  | You can find the latest source at https://downloads.mariadb.org and
database  | the maria-discuss email list at https://launchpad.net/~maria-discuss
database  | 
database  | Please check all of the above before submitting a bug report
database  | at https://mariadb.org/jira
database  | 
database  | 2024-09-10 19:06:22 0 [Note] Starting MariaDB 10.11.8-MariaDB-log source revision 3a069644682e336e445039e48baae9693f9a08ee as process 175
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: The first data file './ibdata1' did not exist. A new tablespace will be created!
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Number of transaction pools: 1
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Using Linux native AIO
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Initializing buffer pool, total size = 256.000MiB, chunk size = 4.000MiB
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Completed initialization of buffer pool
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Setting file './ibdata1' size to 12.000MiB. Physically writing the file full; Please wait ...
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: File './ibdata1' size is now 12.000MiB.
database  | 2024-09-10 19:06:22 0 [ERROR] InnoDB: preallocating 100663296 bytes for file ./ib_logfile101 failed with error 28
database  | 2024-09-10 19:06:22 0 [ERROR] InnoDB: Cannot set log file ./ib_logfile101 size to 96.000MiB
database  | 2024-09-10 19:06:22 0 [ERROR] InnoDB: Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
database  | 2024-09-10 19:06:22 0 [Note] InnoDB: Starting shutdown...
database  | 2024-09-10 19:06:22 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
database  | 2024-09-10 19:06:22 0 [Note] Plugin 'FEEDBACK' is disabled.
database  | 2024-09-10 19:06:22 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded
database  | 2024-09-10 19:06:22 0 [ERROR] Unknown/unsupported storage engine: InnoDB
database  | 2024-09-10 19:06:22 0 [ERROR] Aborting
```

**Comment by psybernoid** [comment]
Thanks for the comment.

The actual folder creation itself doesn't really have any baring in Docker. Because I use QuTS Hero, which by default uses ZFS underneath, thin provsioning is advantageous. Basically it'll boil down to this: do you want all space allocated to the folder right now, or have it grow over time as it fills? You could read this QNAP article if you want to learn more: https://www.qnap.com/en/how-to/faq/article/what-is-the-difference-between-static-volume-thin-volume-and-thick-volume

Either way, whatever method you choose, won't impact Docker itself.

It's not recommended to have a single, monolithic mariaDB container serving multiple different docker containers. I made that mistake some years ago and eventually ran into issues when, for example, I needed to update the mariaDB container and everything that was connected to it crashed.

The recommended practice is to have a mariadb instance per container, define these in the stack. That has the added benefit of making each stack more portable.
Need to move it all to a new server? Simply shut the stack down, tar everything all up, copy to new server and bring it back up again.


Without seeing your full compose config I couldn't possibly comment on why you're get. To get those right, SSH onto your QNAP device and type ting that error, but I would bet on it being related to permissions
To get those right you'd need to SSH onto your QNAP and type `ssh username` where username = whatever username you're using, and ensure that username has appropriate access to the folder. Then, in the compose file set PUID & PGID variables accordingly as documented on https://docs.linuxserver.io/images/docker-mariadb/#usage

Finally. No idea how I set it to dark mode. It might have something to do with the dynamic wallpaper settings you can get to if you click on your username in QTS and go to personal settings.


I'll also add that QuTS Container Station has changed a lot since I wrote this guide. The broad strokes are still correct, but it should now be considered a vague guide now rather than a solid step-by-step. I myself don't actually use Container station at all, instad preferring to edit docker-compose.yml files directly.

**Comment by megamanzteam** [comment]
Well I think thin is the better choice. As for for multiple mariadb, I think I will rework my folders to be configured as so. Also here is the ymal:

```
version: '2.4'
services:
  database:
    image: lscr.io/linuxserver/mariadb
    container_name: database
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=YouCantSeeMe
      - TZ=America/Chicago
    volumes:
      - /container_data/mariadb_database:/config
```
As you can see not much was changed.

**Comment by psybernoid** [comment]
You're not defining PUID & GUID. Also you're not defining a username or database name.

If you're having trouble with getting mariadb to run, I'd suggest looking for support either via their channels, or someplace like /r/selhosted.

**Comment by megamanzteam** [comment]
Ok, was just following your guide here: https://github.com/psybernoid/QNAPDocker#persistant-storage 

```
version: '2.4'
services:
  database:
    image: lscr.io/linuxserver/mariadb
    container_name: database
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kdFkdQZkhxy8n4dJbPA
      - TZ=Europe/London
    volumes:
      - /share/docker-test/database:/config
```
You have no mention of those. I will try the info you provided next. Thanks for all you help.
